### ISSUE TITLE
Persistent store

### ISSUE THREAD

**Issue by flosse** [fanderzon/rust-redux#2]
How would you persist the store?
Let's say there are thousands of users and much more data objects. How would you handle this?

**Comment by fanderzon** [comment]
Interesting question.

As far as I'm concerned Redux only makes proper sense on the client side, where it's perfectly fine to have the state persisted and hydrated through serialization and deserialization.

I should mention this project is an experiment I have not given any serious thought since the week of the hackathon where I made it. If I were to use it for something real, it would be for front end Rust, something I have not had time to do more than dabble in so far.
